/*  http://www.ats.ucla.edu/stat/sas/seminars/sas_survival/  */

TITLE 'PDF OF TIME';
proc univariate data = cancer(where=(status=1));
var time;
histogram time / kernel;
run;

/*PROBABILITY OF DEATH IS STONG INITIALLY BUT THEN TAPERS OFF AS TIME PASSES. */

TITLE 'CDF OF TIME';
proc univariate data = cancer(where=(status=1));
var time;
CDFPLOT time;
run;
TITLE;

/*THE PROBABILITY OF SURVIVING APPROX 500 DAYS OR LESS IS CLOSE TO 50%. THUS, */
/*BY 500 DAYS THE PATIENT HAS ACCUMULATED A LOT OF RISK, WHICH ACCUMULATES */
/*MORE SLOWLY. */


PROC LIFETEST DATA = CANCER (WHERE=(STATUS=1)) PLOTS=S (ATRISK) ;
TIME TIME*STATUS(0);
RUN;

/*THE PROBABILITY OF SURVIVING PAST 650 DAYS IS LESS THAN 20%.*/
/*WHIS IS OPPISITE OF THE CDF, WHERE THE PROBABILITY OF SURVIVING */
/*650 DAYS IS AROUND 80%. */


PROC LIFETEST DATA = CANCER (WHERE=(STATUS=1)) PLOTS=H;
TIME TIME*STATUS(0);
RUN;

/*THE HAZARD STARTS OUT LOW, AND INCREASES SLOWLY UNTIL AROUND 650 DAYS */
/*THERE IS A BIG SPIKE BEFORE THE HAZARD INCREASES AGAIN AT A HIGHER SPEED THAN BEFORE. */
/*IN THE BEGINNING WE WOULD EXPECT AROUND .003 FAILURES PER DAY, AND AROUND 650 DAYS WE SEE*/
/*A SPIKE TO ABOUT .006 FAILURES ANF THEN A GRADUAL INCREASE TO .01*/

ODS OUTPUT PRODUCTLIMITESTIMATES=PLE;
PROC LIFETEST DATA = CANCER (WHERE=(STATUS=1)) NELSON OUTS=OUTCAN;
TIME TIME*STATUS(0);
RUN;

PROC SGPLOT DATA = PLE;
SERIES X=TIME Y=CUMHAZ;
RUN;

/*WE SEE AN INCREASE AT THE BEGINNING OF TIME, AND A COUPLE OF SHARP INCREASES */
/*AROUND 650-1000 DAYS.*/

/*/*/*DATA EXPLORATION*/*/*/;

PROC CORR DATA=CANCER PLOTS(MAXPOINTS=NONE)=MATRIX(HISTOGRAM);
VAR TIME SEX TX GRADE AGE COND SITE T_STAGE N_STAGE;
RUN;

/*OUR AVERAGE SUBJECT: */
/*MALE, APPROX 60.44 YEARS OLD, WITH NO DISABILITIES, ON STANDARD TREATMENT PLAN, */
/*CANCER IS ON TONSILLAR FOSSA, WITH A SINGLE POSITIVE NODE 3+ CM IN DIAMETER NOT FIXED, */
/*AND PRIMARY TUMOR MEASURING MORE THAN 4CM. */

/*THE VARIABLES COND, T_STAGE, AND N_STAGE ARE SIGNIFICANTLY CORRELATED WITH TIME. */



TITLE 'KM ESTIMATES WITH GRAPH';
PROC LIFETEST DATA = CANCER ATRISK PLOTS = S(CB)OUTS=OUTCANKM;
TIME TIME*STATUS(0);
RUN;


TITLE 'NELSON AALEN ESTIMATES';
PROC LIFETEST DATA = CANCER ATRISK NELSON;
TIME TIME*STATUS(0);
RUN;
TITLE;


/*/*/*STATIFY BY TREATMENT? ----- NON PARAMETRIC*/*/*/;
PROC LIFETEST DATA = CANCER ATRISK PLOTS=S(ATRISK CB) OUTS=CANOUT;
STRATA TX;
TIME TIME*STATUS(0);
RUN;



/*/*/*/*/*/*/*/*COX PH MODEL*/*/*/*/*/*/*/*/;

TITLE 'FULL MODEL WITH BACKWARD SELECTION';
PROC PHREG DATA = CANCER;
MODEL TIME*STATUS(0) = SEX TX GRADE AGE COND SITE T_STAGE N_STAGE/SELECTION=BACKWARD;
RUN;
TITLE;

TITLE 'PHREG WITH MODEL SUGGESTION WITH SURVIVAL PLOT';
PROC PHREG DATA = CANCER PLOTS=S;
MODEL TIME*STATUS(0) = COND T_STAGE N_STAGE;
RUN;
TITLE;






